# .github/workflows/deploy.yml
name: Deploy Django to AWS EC2 with Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Keys
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}

    - name: Sync and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
        cd /home/ubuntu/franding
        git pull
        docker stop franding
        docker rm franding
        docker build -t franding .
        docker run -d --name franding -p 8000:8000 franding