name: Deploy to EC2

# main branch push 하기
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
  
    - name: Add EC2 host to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> /Users/gnsdl/.ssh/franding_host
    
    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-northeast-2'
        EC2_INSTANCE_ID: ${{ secrets.EC2_INSTANCE_ID }}
      run: |
        ssh -i /Users/gnsdl/MySite.pem ubuntu@${{ secrets.EC2_HOST }}.ap-northeast-2.compute.amazonaws.com
        sudo apt-get update
        git clone https://github.com/SinMoonGh/2024_franding_project_-.git
        